services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/shift_planner
      PORT: 5000
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://3.238.0.218:5000
    depends_on:
      - backend
    restart: unless-stopped 
volumes:
  mongo_data:
