import React from 'react';
import { useTranslation } from 'react-i18next';
import FinancialSummary from './FinancialSummary';
import PayslipAttendanceTable from './PayslipAttendanceTable';

export default function PayslipDocument({ data }) {
    const { t, i18n } = useTranslation();
    const { employee, period, summary, financials, breakdown } = data;

    return (
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl border border-slate-100 dark:border-slate-700 overflow-hidden print:shadow-none print:border-none print:rounded-none">

            {/* Slip Header */}
            <div className="bg-slate-900 text-white p-8 print:bg-slate-100 print:text-black">
                <div className="flex justify-between items-start">
                    <div>
                        <h2 className="text-3xl font-bold mb-1">{t("payslip.header") || "PAYSLIP"}</h2>
                        <p className="opacity-80 text-sm uppercase tracking-wider">
                            {new Date(period.start).toLocaleDateString(i18n.language, { month: 'long', year: 'numeric' })}
                        </p>
                    </div>
                    <div className="text-right">
                        <p className="font-bold text-lg">{employee.name}</p>
                        <p className="opacity-80 text-sm">{employee.position}</p>
                        <p className="opacity-60 text-xs">{employee.email}</p>
                    </div>
                </div>
            </div>

            <div className="p-8">

                <FinancialSummary
                    financials={financials}
                    summary={summary}
                    currency={data.currency}
                />

                <PayslipAttendanceTable breakdown={breakdown} />

                {/* Print Footer */}
                <div className="hidden print:block mt-12 pt-8 border-t border-gray-200">
                    <p className="text-center text-xs text-gray-500">
                        {t("payslip.generatedBy") || "Generated by ShiftPlanner System on"} {new Date().toLocaleString()}
                    </p>
                </div>

            </div>
        </div>
    );
}
