frontend:
  image: ghcr.io/MohamedKebal2/frontend-app:latest
  replicas: 2
  port: 3000

backend:
  image: ghcr.io/MohamedKebal2/backend-app:latest
  replicas: 2
  port: 5000

mongo:
  image: mongo:6
  port: 27017
  storage: 10Gi

ingress:
  host: ""
  
serviceAccount:
  create: false
  name: ""