frontend:
  image:
    repository: 948580599921.dkr.ecr.us-east-1.amazonaws.com/frontend-app
    tag: latest
  replicas: 2
  port: 80
  env:
    VITE_API_URL: http://backend-service:5000

backend:
  image:
    repository: 948580599921.dkr.ecr.us-east-1.amazonaws.com/backend-app
    tag: latest
  replicas: 2
  port: 5000

mongo:
  image:
    repository: mongo
    tag: 6
  port: 27017
  storage: 10Gi

ingress:
  host: ""

serviceAccount:
  create: false
  name: ""

httpRoute:
  enabled: false

autoscaling:
  enabled: false

service:
  type: ClusterIP
