apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      {{ .Values.backend.labels | toYaml | nindent 6 }}

  template:
    metadata:
      labels:
        {{ .Values.backend.labels | toYaml | nindent 8 }}

    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: MONGO_URI
              value: {{ .Values.backend.env.MONGO_URI | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.backend.requests.cpu }}
              memory: {{ .Values.resources.backend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.backend.limits.cpu }}
              memory: {{ .Values.resources.backend.limits.memory }}