apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: MONGO_URI
              value: {{ .Values.backend.env.MONGO_URI | quote }}
            - name: EMAIL_USER
              value: {{ .Values.backend.env.EMAIL_USER | quote }}
            - name: EMAIL_PASS
              value: {{ .Values.backend.env.EMAIL_PASS | quote }}
            - name: EMAIL_HOST
              value: {{ .Values.backend.env.EMAIL_HOST | quote }}
            - name: EMAIL_PORT
              value: {{ .Values.backend.env.EMAIL_PORT | quote }}
            - name: JWT_ACCESS_SECRET
              value: {{ .Values.backend.env.JWT_ACCESS_SECRET | quote }}
            - name: JWT_REFRESH_SECRET
              value: {{ .Values.backend.env.JWT_REFRESH_SECRET | quote }}
            - name: ACCESS_TOKEN_EXPIRE
              value: {{ .Values.backend.env.ACCESS_TOKEN_EXPIRE | quote }}
            - name: REFRESH_TOKEN_EXPIRE
              value: {{ .Values.backend.env.REFRESH_TOKEN_EXPIRE | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.backend.requests.cpu }}
              memory: {{ .Values.resources.backend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.backend.limits.cpu }}
              memory: {{ .Values.resources.backend.limits.memory }}