apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: frontend
      

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          ports:
            - containerPort: {{ .Values.frontend.port }}

          env:
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.VITE_API_URL | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}