apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    {{ .Values.frontend.labels | toYaml | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
  type: {{ .Values.frontend.service.type }}