apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mern-cluster
  region: us-east-1

managedNodeGroups:
  - name: private-nodegroup1
    instanceType: t3.micro

    desiredCapacity: 2
    minSize: 2
    maxSize: 4

    privateNetworking: true

    subnets:
      - subnet-0d40bc21bfb272549  

    labels:
      role: app

    iam:
      withAddonPolicies:
        albIngress: true